#.github/sync-Python-Actions.GoodInfo.Analyzer.yml
group:
  - files:
      # No. 30-32: Concept stock prices
      - source: raw_conceptstock_daily.csv
        dest:   data/stage1_raw/raw_conceptstock_daily.csv
      - source: raw_conceptstock_weekly.csv
        dest:   data/stage1_raw/raw_conceptstock_weekly.csv
      - source: raw_conceptstock_monthly.csv
        dest:   data/stage1_raw/raw_conceptstock_monthly.csv
      # No. 33-34: Company financials
      - source: raw_conceptstock_company_revenue.csv
        dest:   data/stage1_raw/raw_conceptstock_company_revenue.csv
      - source: raw_conceptstock_company_income.csv
        dest:   data/stage1_raw/raw_conceptstock_company_income.csv
      # No. 35-36: Quarterly segments & overrides
      - source: raw_conceptstock_company_quarterly_segments.csv
        dest:   data/stage1_raw/raw_conceptstock_company_quarterly_segments.csv
      - source: raw_conceptstock_company_segment_overrides.csv
        dest:   data/stage1_raw/raw_conceptstock_company_segment_overrides.csv
      # No. 37: Company metadata
      - source: raw_conceptstock_company_metadata.csv
        dest:   data/stage1_raw/raw_conceptstock_company_metadata.csv
      # Raw column definition document
      - source: raw_column_definition.md
        dest:   raw_column_definition.md
    repos: |
        wenchiehlee-investment/Python-Actions.GoodInfo.Analyzer
